services:
  web:
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media

  worker:
    command: ["celery", "-A", "config", "worker", "--loglevel=INFO", "--concurrency=1"]
    volumes:
      - .:/app
      - media_data:/app/media
