# Generated by Django 6.0.8 on 2026-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='brief_exports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
